/*
 * This source file was generated by the Gradle 'init' task
 */
package five;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int[][] arr = new int[3][3];
        int[][] arr2 = new int[3][3];
        for (int i = 0; i < 3; i++) {
            for (int a = 0; a < 3; a++) {
                System.out.print("Enter Matrix A index of [" + i + "][" + a + "]: ");
                arr[i][a] = sc.nextInt();
            }
        }
        System.out.println("Matrix A is");
        for (int i = 0; i < 3; i++) {
            for (int a = 0; a < 3; a++) {
                System.out.print(arr[i][a] + " ");
            }
            System.out.println();
        }
        for (int t = 0; t < 3; t++) {
            for (int b = 0; b < 3; b++) {
                System.out.print("Enter Matrix B index of [" + t + "][" + b + "]: ");
                arr[t][b] = sc.nextInt();
            }
        }
        System.out.println("Matrix B is");
        for (int t = 0; t < 3; t++) {
            for (int b = 0; b < 3; b++) {
                System.out.print(arr2[t][b] + " ");
            }
            System.out.println();
        }
    }
}